MAIN_MENU = 'main menu'
LOAD_SCREEN = 'load screen'
TIME_OUT = 'time out'
GAME_OVER = 'game over'
Game_Scene = 'game scene'

SIZE_MULTIPLIER = 2.5
BACKGROUND_MULTIPLER = 2.679

BLACK        = (  0,   0,   0)

ITEM_SHEET = 'item_objects'


PLAYER1 = '1 PLAYER GAME'

ORIGINAL_CAPTION = "Five Card Stud"

SCREEN_HEIGHT = 600
SCREEN_WIDTH = 800
SCREEN_SIZE = (SCREEN_WIDTH,SCREEN_HEIGHT)

CURRENT_TIME = 'current time'

PLAYER_NAME = 'player name'
PLAYER_MARIO = 'mario'
PLAYER_LUIGI = 'luigi'

PLAYER1 = '1 PLAYER GAME'
PLAYER2 = '2 PLAYER GAME'

GROUND_HEIGHT = SCREEN_HEIGHT - 62